### PR TITLE
Updated Terms.yml and Foreign.yml

### LINKED ISSUE #48: Duplicated tokens in `Terms.yml`
https://github.com/errata-ai/Microsoft/blob/26acca62396038d7c46a56ea631c2a5261edf767/Microsoft/Terms.yml#L27-L30

Saw some of these tokens are duplicated. What was the intention?

### PR DESCRIPTION
**Pull request by kayx23**
Updated term swapping suggestions in Terms.yml. Removed and updated tokens that are duplicated, unclear, or not meaningful. For details please see changed files.

Fixes #48

### CODE REVIEW

**Comment by kayx23** [comment]
One of the removed swapping suggestion is bps (basis points). I don't think it makes sense to suggest against the use of the shorthand form `bps`.

**Comment by jdkato** [comment]
Please cite the style guide for removals or additions -- it's not about what you or I deem meaningful.

For example, the guide [explicitly states](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/alphanumeric) to not use "alphanumerical" which you've removed.

**Comment by kayx23** [comment]
> the guide [explicitly states](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/alphanumeric) to not use "alphanumerical" which you've removed.

First of all, I believe the following means to swap A for B?
```
swap:
    A:B
```
If that's true, the previous rule around `alphanumerical` was:
```
swap:
    alphanumerical: alphanumeric
```
which means to use `alphanumerical` over `alphanumeric`, the exact opposite of what it supposed to be?

**Comment by kayx23** [comment]
Thanks for the resource. Weirdly interesting to learn that `Drive C` is recommended over `C Drive`... 

I went through the relevant docs for my changes. 

1. For `artificial intelligence: AI`:

> To refer to the technology itself, use AI for all audiences and in most content, including blogs, websites, and email. Don't spell out artificial intelligence. "

https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/ai-bot-terms

2. For `'(?:assembler|machine language)': assembly language`:

https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/assembly-language

3. For `bps` and `bpp`: 

Didn't find any doc supporting if they should be in other forms. Did not even find what `bpp` stands for.

**Comment by kayx23** [comment]
Also, any recommended way to add a link (or with any other way) to let new users know term rules here are defined based off the microsoft style guide a-z word lists? 

I see reference could be provided using `link:`, such as
`link: https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/adapter`

Perhaps we can add something like this with a comment saying rules for other terms could be found in the same guide?

**Comment by jdkato** [comment]
> Also, any recommended way to add a link (or with any other way) to let new users know term rules here are defined based off the microsoft style guide a-z word lists?
> 
> I see reference could be provided using `link:`, such as `link: https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/adapter`
> 
> Perhaps we can add something like this with a comment saying rules for other terms could be found in the same guide?

👍

**Comment by jdkato** [comment]
Looks good. Thanks!

**Pull request merged**
